name: dart_algorithms_and_data_structures
description: Algorithms and Data Structures implemented in Dart.
version: 1.0.0
repository: https://github.com/AhmedLSayed9/dart_algorithms_and_data_structures

environment:
  sdk: '>=2.19.3 <3.0.0'

dependencies:
  characters: ^1.3.0
  collection: ^1.17.1

dev_dependencies:
  lints: ^2.0.1
  test: ^1.24.1
