name: dart_algorithms_and_data_structures
description: Algorithms and Data Structures implemented in Dart.
version: 1.0.0
repository: https://github.com/AhmedLSayed9/dart_algorithms_and_data_structures

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  characters: ^1.3.0
  collection: ^1.17.2

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.2
